config/routes.rb
Rails.application.routes.draw do

  get '/adminlogin',to:'adminsession#new'

  post '/adminlogin',to:'adminsession#create'

  delete '/adminlogout',to:'adminsession#destroy'

  get '/adminhome',to:'admin#home'

  get '/adminemployee',to:'admin#index'

  get '/adminedit',to:'admin#edit'

  patch '/adminedit', to: 'admin#update'

  get '/adminproject',to:'admin#projects'

  get  '/addemployee',  to: 'admin#addemployee'
  
  post '/addemployee',  to: 'admin#create'

  get '/showemployee',to:'admin#show'
  
  post '/showemployee',to:'admin#show'

  get '/home',to:'employees#home'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'employees#edit', fb: true, logout: false


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'  
  resources :employees 
end

app/views/admin/addemployee.html.erb
<% provide(:user, 'admin') %>
<h1>Add Employee</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@employee, url: addemployee_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :designation %>
      <%= f.text_field :designation, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', id: "email" %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :gender %>
      <%= f.select :gender,[['Male'],['Female'],['Other']], class: 'form-control' %>

      <%= f.label :dateofjoin, "Date of Join"%>
      <%= f.date_field :dateofjoin, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :active%><br />
      <%= f.check_box :active,id: 'active' %><br />

      <%= f.label :username %>
      <%= f.email_field :username, class: 'form-control', id: "username" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Add Employee", class: "btn btn-primary" %>
      <br><br><%= link_to "Cancel", adminemployee_path, class: "btn btn-lg btn-primary can" %>
    <% end %>
  </div>
</div>

<script>
$(document).ready(function() {
    $('#email').blur(function(){
      $('#username').val($('#email').val());
    });
});

</script>

app/views/admin/edit.html.erb
<% provide(:user, 'admin') %>
<% if logged_in? %>
<h1>Update Details</h1>
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(@employee, url: adminedit_path(:id => @employee.id), method: :patch) do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :designation %>
      <%= f.text_field :designation, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :gender %>
      <%= f.text_field :gender, class: 'form-control', readonly:"readonly" %>

      <%= f.label :dateofjoin, "Date of Join"%>
      <%= f.date_field :dateofjoin, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %> 

      <%= f.label :active%><br/>
      <%= f.check_box :active, id: 'active' %><br/>  

      <%= f.submit "Update", class: "btn btn-primary" %>
      <br><br><%= link_to "Cancel", adminemployee_path, class: "btn btn-lg btn-primary can" %>
    <% end %>  
  </div>
</div>
<% end %>

app/views/admin/home.html.erb
<% provide(:user, 'admin') %>
<% if logged_in? %>
<h1>Welcome to Employee Portal</h1>
<% end %>

app/views/admin/index.html.erb
<% provide(:user, 'admin') %>
<% if logged_in? %>
<table class="table table-striped">

  <tr class>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Active</th>
    <th colspan="3"></th>
  </tr>

  <% @employee.each do |employee| %>
  <% if !employee.admin %>
  <tr>
    <td><%= link_to employee.name ,showemployee_path(:id=>employee.id) ,method: :post%></td>
    <td><%= employee.email %></td>
    <td><%= employee.phone %></td>
    <td><%= employee.active %></td>
    <td><%= link_to 'Edit', adminedit_path(:id => employee.id) %></td>
    <td><%= link_to 'Delete', employee, method: :delete,
                                   data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
  <% end %>
</table>
<br>

<%= link_to 'Add Employee', addemployee_path,class:"btn btn-primary pull-right" %>

<%= will_paginate  @employee%>
<% end %>

app/views/admin/new.html.erb
<% provide(:title, "Log in") %>
<% provide(:user, 'admin') %>
<!-- <h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
      
  </div>
</div> -->

app/views/admin/projects.html.erb
<% provide(:user, 'admin') %>

app/views/admin/show.html.erb
<% provide(:user, 'admin') %>
<%= image_tag @employee.image.thumb.url, :class => 'img' unless @employee.image.blank? %>
<table class="table table-striped">

    <tr>
      <td>Employee Id</td>
      <td>
          RP<%= @employee.id%>
      </td>
    </tr>
    <tr>
      <td>Name</td>   
      <td>
          <%= @employee.name %>
      </td>
    </tr>
    <tr>
      <td>Email</td>
      <td>
          <%= @employee.email %>
      </td>
    </tr>
    <tr>  
      <td>Designation</td>
      <td>
          <%= @employee.designation %>
      </td>
    </tr>
    <tr>
      <td>Address</td>
      <td>
          <%= @employee.address %>
      </td>
    </tr>
    <tr>
      <td>Username</td>
      <td>
          <%= @employee.username%>
      </td>
    </tr>
    <tr>
      <td>Personal Email</td>
      <td>
          <%= @employee.personalemail%>
      </td>
    </tr>
    <tr>
      <td>Date of Join</td>
      <td>
          <%= @employee.dateofjoin %>
      </td>
    </tr>
    <tr>
      <td>Date of Birth</td>
      <td>
          <%= @employee.dateofbirth %>
      </td>
    </tr>
    <tr>
      <td>Active</td> 
      <td>
          <%= @employee.active%>
      </td>
    </tr>
    <tr>
      <td>Phone</td>
      <td>
          <%= @employee.phone%>
      </td>
    </tr>

</table>