config/routes.rb
Rails.application.routes.draw do

  get '/adminlogin',to:'adminsession#new'

  post '/adminlogin',to:'adminsession#create'

  delete '/adminlogout',to:'adminsession#destroy'

  get '/adminhome',to:'admin#home'

  get '/adminemployee',to:'admin#index'

  get '/adminedit',to:'admin#edit'

  patch '/adminedit', to: 'admin#update'

  get '/adminproject',to:'admin#projects'

  get  '/addemployee',  to: 'admin#addemployee'
  
  post '/addemployee',  to: 'admin#create'

  get '/showemployee',to:'admin#show'
  
  post '/showemployee',to:'admin#show'

  get '/home',to:'employees#home'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'employees#edit', fb: true, logout: false


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'  
  resources :employees 
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "Employee Portal",'/login', id: "logo"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if yield(:user) == "employee"%>
          <% if logged_in? %>
            <li>
              <li><%= link_to "Home",   home_path %></li>
              <li><%= link_to "Details",   edit_employee_path(current_employee) %></li>
              <li><%= link_to "Log Out", logout_path,method: :delete %></li>
            </li> 
          <% end %>
        <% elsif yield(:user) == "admin" %>
          <% if logged_in? %>
            <li>
              <li><%= link_to "Home",   adminhome_path %></li>
              <li><%= link_to "Employees",  adminemployee_path%></li>
              <li><%= link_to "Projects",   adminproject_path %></li>
              <li><%= link_to "Log Out",adminlogout_path,method: :delete %></li>
            </li> 
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '{your-app-id}',
          cookie     : true,
          xfbml      : true,
          version    : '{latest-api-version}'
        });
          
        FB.AppEvents.logPageView();   
          
      };
    
      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
  </body>
</html>